general {
    lock_cmd = noctalia msg session lock
    inhibit_sleep = 3
}

listener {
    timeout = 1800 # 30mins
    on-timeout = noctalia msg session lock
}

listener {
    timeout = 2700 # 45mins
    on-timeout = noctalia msg dpms-off
    on-resume = noctalia msg dpms-on ; notify-send "welcome back!"
}

listener {
    timeout = 3600 # 1hr
    on-timeout = systemctl suspend
