-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--################

--## AUTOSTART ###

--################

-- change inside () to your terminal emulator.
local terminal = ("kitty")


hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("kitty")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("noctalia")

    hl.exec_cmd("sleep 1 && " .. os.getenv("HOME") .. "/.config/hypr/scripts/wallpapers/set-random.sh")
end)
