-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Variables
local inFocusOpacity = 0.9
local notInFocusOpacity = 0.7

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Default opacity for all windows
hl.window_rule({
    name = "opacity-default",
    match = {
        class = ".*",
    },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})

-- Kitty fully opaque
hl.window_rule({
    name = "opacity-kitty",
    match = {
        class = "^kitty$",
    },
    opacity = "1.0 1.0",
})

-- Browsers
hl.window_rule({
    name = "opacity-browsers",
    match = {
        class = "^(firefox|brave|chromium|librewolf|qutebrowser|zen-browser)$",
    },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})

-- Spotify / Discord / Telegram / VS Code / Thunar or Nemo by title
hl.window_rule({
    name = "opacity-spotify",
    match = { title = ".*Spotify.*" },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})
hl.window_rule({
    name = "opacity-discord",
    match = { title = ".*Discord.*" },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})
hl.window_rule({
    name = "opacity-telegram",
    match = { title = ".*Telegram.*" },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})
hl.window_rule({
    name = "opacity-vscode",
    match = { title = ".*Code.*" },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})
hl.window_rule({
    name = "opacity-filemanager",
    match = { title = ".*(Thunar|nemo).*" },
    opacity = inFocusOpacity .. " " .. notInFocusOpacity,
})

-- Lunar Client fullscreen (static effect)
hl.window_rule({
    name = "fullscreen-lunar-client",
    match = {
        class = "^Lunar Client.*$",
    },
    fullscreen = true,
})
